#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#   username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    properties:
      javax:  
        persistence:
          validation: 
            mode: none